### PR TITLE
add xlarge to dialog

### PR DESCRIPTION
**Pull request by benbaler**

### CODE REVIEW

**Comment by benbaler** [comment]
@omrihecht i took it from the app.

**Comment by omrihecht** [comment]
@benbaler , let's try and look for a way to have xLarge responsive to the window instead of fixed width

**Comment by benbaler** [comment]
@omrihecht @danazelniker done

**Comment by doroncy** [comment]
@benbaler i havent seen in invision xLarge dialog, for which feature this was wanted?

**Comment by benbaler** [comment]
@doroncy this is for docs 2.0 preview doc

**Pull request merged**
